# -*- coding: utf-8 -*-
"""outputhead.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P6XQFLNzpega4EAFNwiV1Dd9ua-UrAXe
"""

import tensorflow as tf

class OutputHead(tf.keras.layers.Layer):
    def __init__(self, vocab_size):
        super().__init__()
        self.layernorm = tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.out_head  = tf.keras.layers.Dense(vocab_size)

    def call(self, x):
        y = self.layernorm(x)
        y = self.out_head(y) # (batch_size, seq_len, vocab_size)
        return y

